[package]
name = "aptos-network2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aptos-types = { workspace = true }
tokio = { workspace = true }
